/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actions/repo-priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update repository priority order and pause states */
        post: operations["Api_updateRepoPriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/runner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Manual runner controls: stop a runner, spawn an extra runner, or pause dispatch */
        post: operations["Api_controlRunner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel, re-run, or re-run failed workflow runs via GitHub API */
        post: operations["Api_triggerWorkflowAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get multi-tier host and package cache usage statistics */
        get: operations["Api_getCacheStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Evict specific cache categories or purge entire host cache */
        post: operations["Api_purgeCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current fleet state, active runners, and queued workflow jobs */
        get: operations["Api_getFleet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get in-memory daemon circular log lines */
        get: operations["Api_getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get live effective system settings and origins */
        get: operations["Api_getSettings"];
        put?: never;
        /** @description Mutate system settings dynamically at runtime without requiring restart */
        post: operations["Api_updateSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current system and autoscaler status (alias of getFleet) */
        get: operations["Api_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Server-Sent Events real-time event stream */
        get: operations["Api_streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description GitHub Actions billing summary */
        ActionsBilling: {
            /** Format: int32 */
            included_minutes?: number;
            /** Format: int32 */
            total_minutes_used?: number;
            /** Format: int32 */
            total_paid_minutes_used?: number;
        };
        /** @description Storage usage for a specific cache category */
        CacheCategoryUsage: {
            category: string;
            /** Format: int64 */
            bytes: number;
            human_readable: string;
        };
        /** @description Cache purge request */
        CachePurgeRequest: {
            category?: string;
            repo?: string;
            all?: boolean;
        };
        /** @description Overall cache statistics */
        CacheStats: {
            /** Format: int64 */
            total_bytes: number;
            total_human: string;
            categories: components["schemas"]["CacheCategoryUsage"][];
        };
        /** @description Generic error response */
        ErrorResponse: {
            error: string;
            details?: string;
        };
        /** @description Complete snapshot of the fleet, runner slots, and job queues */
        FleetState: {
            runners: components["schemas"]["RunnerInfo"][];
            queued_jobs: components["schemas"]["QueuedJob"][];
            /** Format: int32 */
            busy_runners: number;
            /** Format: int32 */
            max_runners: number;
            /** Format: int32 */
            free_slots: number;
            repo_priority: string[];
            paused_repos: string[];
            /** Format: int32 */
            rate_limit_remaining?: number;
            /** Format: int32 */
            rate_limit_limit?: number;
            actions_billing?: components["schemas"]["ActionsBilling"];
        };
        /** @description Log line entry */
        LogEntry: {
            timestamp: string;
            message: string;
        };
        /** @description Logs response payload */
        LogsResponse: {
            logs: components["schemas"]["LogEntry"][];
        };
        /** @description Information about a queued or running workflow job */
        QueuedJob: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            run_id: number;
            name: string;
            workflow_name?: string;
            head_branch?: string;
            /** Format: int32 */
            run_attempt?: number;
            status: ("queued" | "in_progress") | string;
            created_at?: string;
            started_at?: string;
            labels: string[];
            html_url: string;
            repo: string;
            /** Format: int32 */
            queue_position?: number | null;
            waiting_reason?: string;
            run_url?: string;
            runner_name?: string;
            stages_done?: number;
            stages_total?: number;
            steps_completed?: number;
            steps_total?: number;
            current_step?: string;
            progress_pct?: number;
        };
        /** @description Update payload for repository priority ordering and pause states */
        RepoPriorityAction: {
            priority: string[];
            paused: string[];
        };
        /** @description Manual runner control action */
        RunnerControlAction: {
            runner_id?: string;
            /** @enum {string} */
            action: "start" | "stop" | "drain" | "pause" | "resume";
            repo?: string;
            arch?: string;
        };
        /** @description Information about an ephemeral runner instance */
        RunnerInfo: {
            id: string;
            name: string;
            status: string;
            state: string;
            target_repo: string;
            target_arch: string;
            backend: string;
            created_at?: string;
            /** Format: int64 */
            job_id?: number;
            /** Format: int64 */
            run_id?: number;
            job_url?: string;
            run_url?: string;
            job_name?: string;
            workflow_name?: string;
            stages_done?: number;
            stages_total?: number;
            steps_completed?: number;
            steps_total?: number;
            current_step?: string;
            progress_pct?: number;
        };
        /** @description Generic success response */
        SuccessResponse: {
            ok: boolean;
            message?: string;
        };
        /** @description Live runtime system configuration */
        SystemSettings: {
            access_token_configured?: boolean;
            access_token?: string;
            owner?: string;
            org?: string;
            auto_discover?: boolean;
            /** Format: int32 */
            active_days?: number;
            runner_backend?: string;
            auto_route_vm?: boolean;
            vm_trigger_labels?: string[];
            docker_network?: string;
            runner_arch?: string;
            /** Format: int32 */
            min_runners?: number;
            /** Format: int32 */
            max_runners?: number;
            /** Format: int32 */
            runner_cpus?: number;
            runner_memory?: string;
            /** Format: int32 */
            poll_interval?: number;
            /** Format: int32 */
            discovery_interval?: number;
            proxies_enabled?: boolean;
            cache_enabled?: boolean;
            host_cache_dir?: string;
            native_arch_override?: string;
        };
        /** @description Workflow run action request (cancel, re-run, or re-run failed) */
        WorkflowActionRequest: {
            repo: string;
            /** Format: int64 */
            run_id: number;
            /** @enum {string} */
            action: "cancel" | "rerun" | "rerun-failed";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Api_updateRepoPriority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepoPriorityAction"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_controlRunner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunnerControlAction"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_triggerWorkflowAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_getCacheStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStats"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_purgeCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CachePurgeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_getFleet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetState"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_getLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettings"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettings"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetState"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Api_streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
